#!/bin/bash
# Variables
remote="10.10.10.187"
user="andre"
remote_server="$user@$remote"
sour_conf_path="/var/opt/CrushFTP10"
sour_data_path="/media/Logs"
dist_conf_path="/media/crushftp/"
dist_data_path="/media/"
r_opt="-azvP"

#below script not asking any password
rsync $r_opt -e ssh $remote:/$sour_conf_path/users/MainUsers $dist_conf_path
rsync $r_opt -e ssh $remote:/$sour_conf_path/WebInterface/images/logo* $dist_conf_path
rsync $r_opt -e ssh $remote:/$sour_conf_path/WebInterface/favicon.ico $dist_conf_path
#rsync $r_opt -e ssh $remote:/$sour_data_path $dist_data_path